*** Settings ***
Documentation                   df26-copado-cicd-flow-2026-09-15 -- every interaction in the order it was driven live,
...                              with the page it ran on, the transition it caused and the page state it needed.
...                              Generated by tools/recorder/pom/export_flow.py from the recorded session; edit the
...                              session or the store, never this file by hand.
Resource                        ../../resources/common.robot
Suite Setup                     Setup Browser
Suite Teardown                  End suite

*** Test Cases ***
df26-copado-cicd-flow-2026-09-15
    # Dreamforce 2026 Copado CI/CD demo flow driven live 2026-09-15: User Story record -> Commit Experience (Get Changes, search, Compare, Explain Changes, row tick, Dependency Analysis, AI Select Changes) and Revenue Cloud Settings on US-0001043. Rebuilt from the kept --op kw session plus the --op py drives, with effects (leads_to / opens) and page states as observed. Verdicts are the live ones; CAUGHT-BUG rows are locator lessons, not page defects.
    ${token}=    JwtAuthenticate    ${client_idCICD}    ${usernameCICD}    ${private_keyCICD}
    JwtLogin

    # PAGE: cicd-demo|/lightning/r/copado__User_Story__c/{id}/view
    GoTo    https://copado-se-demo.lightning.force.com/lightning/r/copado__User_Story__c/a1v7Q000001LJnRQAW/view
    # PASS-GUARDED
    VerifyText    User Story
    # PASS-GUARDED -- opens the Commit Experience (a separate Angular app) in the same tab, ~5 s
    ClickText    Commit Changes
    # TRANSITION: cicd-demo|/lightning/r/copado__User_Story__c/{id}/view -> na.devops.copado.com|/en/commit/{id}

    # PAGE: na.devops.copado.com|/en/commit/{id}
    #   state 'loading': header 'Commit Changes: Loading...' then 'Commit Changes: US-...'; Destination badge 'Loading...'
    #   state 'changes-listed': after Get Changes: 'N of 1178 items selected'; Dependency Analysis DISABLED
    #   state 'row-selected': a row ticked: Dependency Analysis reads 'Analyzing dependencies' then enables (auto-runs on selection)
    #   state 'dependency-panel': panel 'Dependency Analysis' / 'Dependencies' open: Show All Dependencies toggle, Add Selections (n)
    #   state 'dependencies-analysed': panel closed: button label 'Dependency Analysis (2)' with a warning icon
    #   state 'compare-panel': panel 'Flow: <name>' open: spinner, then diagram with Changes strip and Explain Changes
    #   state 'agent-thinking': Orchestrate Agent panel: 'Thinking...' / 'AI is analyzing the changes...'; Stop button
    #   state 'agent-done': streaming finished: Copy button, no Stop; Select Changes adds a green 'Smart Changes analysis completed!' toast and a 'Recommended Components' table; Explain Changes shows tabs Changes / Impact & Risk / Recommendations
    # STATE: loading
    # PASS-GUARDED
    VerifyText    Find Metadata
    # PASS-GUARDED -- 1,178 items; the Dependency Analysis button is disabled until a row is ticked
    ClickText    Get Changes
    # STATE -> changes-listed
    # PASS-GUARDED
    TypeText    Search    Opportunity_Creation
    # PASS-GUARDED
    VerifyText    Opportunity_Creation_Automation    partial_match=True
    # VERIFIED-PASS
    ClickElement    //cds-table-row[.//span[normalize-space()\='Opportunity_Creation_Automation']][.//span[normalize-space()\='Flow']]//cds-table-cell[@role\='button']
    # TRANSITION: opens panel 'Flow: Opportunity_Creation_Automation' on na.devops.copado.com|/en/commit/{id}
    # STATE: compare-panel
    # PASS-GUARDED
    VerifyText    Flow: Opportunity_Creation_Automation
    # COULD-NOT-CHECK: clicked before the diagram finished rendering; the Orchestrate Agent panel did not open (no 'What Changed' 20 s later). Wait for the Changes strip before clicking.
    # ClickText    Explain Changes
    # CAUGHT-BUG: the visible text is CSS text-transform: uppercase; the DOM text is title case. A label a person sees in caps is not the label QWeb matches (measured 2026-09-15).
    # VerifyText    WHAT CHANGED    partial_match=True
    # CAUGHT-BUG: click_checkbox by the aria-label found nothing in 15 s: the cds-checkbox host carries the aria-label, the input inside it does not; the xpath //cds-checkbox[@aria-label='Select row Flow:Opportunity_Creation_Automation']//input resolves
    # ClickCheckbox    Select row Flow:Opportunity_Creation_Automation
    # COULD-NOT-CHECK: bad positional args (timeout None) -- caller error, not a page fact
    # ClickText    Dependency Analysis    1    None    True
    # COULD-NOT-CHECK: the dependency panel was never opened (step 11 failed)
    # VerifyText    Show All Dependencies
    # VERIFIED-PASS
    ClickElement    //button[@aria-label\='Close diff']
    # STATE -> changes-listed
    # VERIFIED-PASS
    ClickElement    //cds-checkbox[@aria-label\='Select row Flow:Opportunity_Creation_Automation']//input
    # STATE -> row-selected
    # PASS-GUARDED
    ClickText    Dependency Analysis
    # TRANSITION: opens panel 'Dependency Analysis' on na.devops.copado.com|/en/commit/{id}
    # STATE: dependency-panel
    # PASS-GUARDED
    VerifyText    Show All Dependencies
    # PASS-GUARDED
    VerifyText    Opportunity.Bypass_Auto_Naming__c
    # VERIFIED-PASS
    ClickElement    //*[normalize-space()\='Dependency Analysis']/following::button[1]
    # STATE -> dependencies-analysed
    # PASS-GUARDED -- the AI Select Changes button (class btn-ai); the Orchestrate Agent panel opens in the 'Thinking...' state
    ClickText    Select Changes
    # TRANSITION: opens panel 'Orchestrate Agent' on na.devops.copado.com|/en/commit/{id}
    # STATE: agent-thinking
    # PASS-GUARDED
    VerifyText    AI is analyzing the changes    partial_match=True
    # STATE: agent-done
    # CAUGHT-BUG: the visible text is CSS text-transform: uppercase; the DOM text is title case. A label a person sees in caps is not the label QWeb matches (measured 2026-09-15).
    # VerifyText    RECOMMENDED COMPONENTS    partial_match=True
    # PASS-GUARDED
    VerifyText    Recommended Components
    # PASS-GUARDED -- green toast 'Smart Changes analysis completed! Found 20 recommended components.' marks the done state; Copy present, Stop gone
    VerifyText    Smart Changes analysis completed    partial_match=True
    # VERIFIED-PASS
    ClickElement    //*[normalize-space()\='Orchestrate Agent']/following::button[1]
    # STATE -> dependencies-analysed
    # VERIFIED-PASS
    ClickElement    //cds-table-row[.//span[normalize-space()\='Opportunity_Creation_Automation']][.//span[normalize-space()\='Flow']]//cds-table-cell[@role\='button']
    # TRANSITION: opens panel 'Flow: Opportunity_Creation_Automation' on na.devops.copado.com|/en/commit/{id}
    # STATE: compare-panel
    # CAUGHT-BUG: 'Additions (4)' is not one text node: the word and the count are separate elements. Verify 'Additions' alone.
    # VerifyText    Additions (4)
    # PASS-GUARDED
    ClickText    Explain Changes
    # TRANSITION: opens panel 'Orchestrate Agent' on na.devops.copado.com|/en/commit/{id}
    # STATE: agent-thinking
    # PASS-GUARDED
    VerifyText    Orchestrate Agent
    # STATE: agent-done
    # PASS-GUARDED -- DOM text 'What Changed' inside <strong>, CSS uppercase; tabs Changes / Impact & Risk / Recommendations; Copy present
    VerifyText    What Changed
    # PASS-GUARDED
    VerifyText    Impact & Risk

    # PAGE: cicd-demo|/lightning/r/copado__User_Story__c/{id}/view
    # PASS-GUARDED
    VerifyText    Revenue Management - RCA - New product configuration
    # PASS-GUARDED -- a Lightning quick action (copado_labs__Revenue_Cloud_Deployment_Configuration): the URL becomes /lightning/action/quick/... with backgroundContext, so the modal is its own page key
    ClickText    Revenue Cloud Settings
    # TRANSITION: opens modal 'Revenue Cloud Deployment Configuration' on cicd-demo|/lightning/r/copado__User_Story__c/{id}/view
    # TRANSITION: the modal is its own page: cicd-demo|/lightning/action/quick/copado__User_Story__c.copado_labs__Revenue_Cloud_Deployment_Configuration

    # PAGE: cicd-demo|/lightning/action/quick/copado__User_Story__c.copado_labs__Revenue_Cloud_Deployment_Configuration
    #   state 'opening': modal paints the title alone first
    #   state 'open': Target: <env>, tabs Standard Rules (n) / Advanced Rules (n) / Automations (n), filters, rows, Add Changes
    # PASS-GUARDED
    VerifyText    Revenue Cloud Deployment Configuration
    # CAUGHT-BUG: the tab's count sits in the same text node ('Standard Rules\n2'); exact verify resolved the superstring and the read-back guard refused it (SilentWrongValue). partial=True is the honest form.
    # VerifyText    Standard Rules
    # CAUGHT-BUG: the tab's count sits in the same text node ('Standard Rules\n2'); exact verify resolved the superstring and the read-back guard refused it (SilentWrongValue). partial=True is the honest form.
    # VerifyText    Advanced Rules
    # CAUGHT-BUG: the tab's count sits in the same text node ('Standard Rules\n2'); exact verify resolved the superstring and the read-back guard refused it (SilentWrongValue). partial=True is the honest form.
    # VerifyText    Automations
    # PASS-GUARDED
    VerifyText    Add Changes
    # PASS-GUARDED
    VerifyText    Standard Rules    partial_match=True
    # PASS-GUARDED
    VerifyText    Advanced Rules    partial_match=True
    # PASS-GUARDED
    VerifyText    Automations    partial_match=True
    # VERIFIED-PASS
    ClickElement    //button[contains(@class,'slds-modal__close')]
    # TRANSITION: cicd-demo|/lightning/action/quick/copado__User_Story__c.copado_labs__Revenue_Cloud_Deployment_Configuration -> cicd-demo|/lightning/r/copado__User_Story__c/{id}/view
